version: "3.8"

services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jobportal-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app                # Mount code
      - /app/node_modules     # Prevent host overwrite
    networks:
      - app-network

networks:
  app-network:
